New Next.js tutorial
talkjs/tutorials pull request #12
Opened 2024-06-20 07:35 UTC by keerlu

New Next.js tutorial to replace the [current one](https://talkjs.com/resources/add-chat-to-a-next-js-app-with-talkjs-tutorial/) on the Resources site. Based on the React getting started guide with some changes for server side rendering.

More details in Slack conversation [here](https://talkjs.slack.com/archives/C05N5AYM353/p1718704145474759).

2024-06-20 11:37 UTC, Asha20 requested changes
This looks good! I'm not sure whether you meant to add images after my review or before, so I figured I'd mention them in the comments just in case you forgot.

2024-06-20 12:30 UTC, keerlu commented on add-chat-to-a-nextjs-app-with-talkjs/add-chat-to-a-nextjs-app-with-talkjs.md
> +</figure>
Thanks! I'll add these when I upload to Ghost, but I forgot to leave notes here

2024-06-20 12:45 UTC, keerlu commented on add-chat-to-a-nextjs-app-with-talkjs/add-chat-to-a-nextjs-app-with-talkjs.md
> +```
Thanks! Fixed

2024-06-20 14:27 UTC, Asha20 approved these changes

2024-06-21 07:27 UTC, csmeyns approved these changes
Great! Super clear and accessible :) Two tiny presentation suggestions but just see whether you'd want to take those over or no

2024-06-21 07:27 UTC, csmeyns commented on add-chat-to-a-nextjs-app-with-talkjs/add-chat-to-a-nextjs-app-with-talkjs.md
> +We'll follow a very similar approach to our to our [React getting started guide](https://talkjs.com/docs/Getting_Started/Frameworks/React/1_On_1_Chat), but there will be some differences because of N
I wonder whether it would also be an option to introduce the JavaScript SDK and client components later, when they're first used (in the 'Create new users and conversations' section)? As the info about all the tools/systems could be a bit overwhelming at the outset? Not essential, just a thought :)

2024-06-21 07:27 UTC, csmeyns commented on add-chat-to-a-nextjs-app-with-talkjs/add-chat-to-a-nextjs-app-with-talkjs.md
> +You'll probably also have an existing Next.js app that you want to add TalkJS to. If not, you can [create a Next.js starter app](https://nextjs.org/docs/getting-started/installation).
I think I'd prefer to phrase this as "You'll also need an existing Next.js app ...", or smth like that, rather than the assumption that a person already has it. As someone who doesn't have their Next.js app ready yet might otherwise feel they're already falling short 🥲

2024-06-21 08:14 UTC, keerlu commented on add-chat-to-a-nextjs-app-with-talkjs/add-chat-to-a-nextjs-app-with-talkjs.md
> +We'll follow a very similar approach to our to our [React getting started guide](https://talkjs.com/docs/Getting_Started/Frameworks/React/1_On_1_Chat), but there will be some differences because of N
Yeah, I'm not a  massive fan of this infodump of technical stuff here either, it is a bit clunky and potentially overwhelming. In this case I think it's worth it to be upfront at the start with how server-side rendering in Next.js changes things, rather than hiding it in the middle somewhere.

2024-06-21 08:14 UTC, keerlu commented on add-chat-to-a-nextjs-app-with-talkjs/add-chat-to-a-nextjs-app-with-talkjs.md
> +You'll probably also have an existing Next.js app that you want to add TalkJS to. If not, you can [create a Next.js starter app](https://nextjs.org/docs/getting-started/installation).
Yeah good point, I'll tweak the wording!

2024-10-18 14:46 UTC, merged